### PR TITLE
Publish strides

### PR DESCRIPTION
**Pull request by cosama**
This will allow to configure (to some extend) the publish rate of different topics. This is achieved through individual stride parameters that define how many data packages will be skipped before a message is published on a given topic.

I have tested this with a VN200, all with different strides and it works fine.

### CODE REVIEW

**Comment by dawonn** [comment]
I'm slightly hesitant here... In general I want the device interface node to be as simple as possible so as to make it easy to audit for correctness, and less features / LOC should help reduce bug count. (Not to say you made a mistake, but I worry a little bit about feature-creep in general) 

Could you use ROS message_filters (or similar)? Or make a node that filters these down so that this logic doesn't need to be included in the core driver node? 

Or use the BOR register 2 and 3 with different update rates for sets of packets. Sure you can't set each topic to a different rate, but I would think that three different rates would be pretty sufficient for most use cases....

**Comment by cosama** [comment]
I tried the bor register solution (that was my first thought too), but it didn't fair well with respect to constant time intervals between messages, the slower one threw the faster one off and introduced delays of about 2-3milliseconds there. 

You certainly could use a ROS message filter of some sort, but I feel that might introduce a lot of overhead, you already have all that ROS communication going on once the messages are out.

I agree with you that there is a lot of additional parameters here, wasn't sure what was the best approach would be. I tried to keep it as general as possible, but I think that might not be necessary. I feel the only message that you ever need (I certainly do) at a different rate is the IMU (really high to enable simultaneous localization and mapping).

So I could only have one stride for none IMU messages, if that is more agreeable to you (would actually prefer that myself). Not sure about the name, maybe `none_imu_topics_stride` or `none_imu_topics_rate_divisor`. That way it is only one more parameter. Alternatively, we could also have a `imu_rate_multiplier` and maybe rename `async_output_rate` to `publish_rate`?

This will be actually the last of my changes for now :smile. Then it would be sufficient for all the applications we currently have in our group (we do a lot of SLAM, so we need that high IMU rate, but we won't have all the other stuff at 200Hz). I understand if it goes to far and I can keep it in my own fork for now. I really appreciate the responsiveness here and would happily accept if you think it is a 'feature' to much :laughing:

**Comment by cosama** [comment]
@dawonn I wanted to check in what your thought are on my suggestion above of only having the option to configure the imu rate, next to the other messages.

Unfortunately recent changes, particularly https://github.com/dawonn/vectornav/pull/92 would require me to pretty much rewrite the whole thing again, if you agree that that would be okay. Would have been great to get that in before the formatting changes.

**Comment by dawonn** [comment]
🤔 hmmm....

It doesn't add a lot of code or complexity so if you believe it's valuable for the wider community then please refactor and I'll accept it.


(I personally would prefer that this sort of logic happens in an external message filter or via the BOR, but if you have some data that indicates that is impractical we should definitely proceed with this feature.)

**Comment by cosama** [comment]
@dawonn Thanks for the quick reply. I agree with the BOR approach, but as mentioned it interferes with having a consistent publish rate, also I am not sure if that approach would work together with changes introduced in https://github.com/dawonn/vectornav/pull/91.

This http://wiki.ros.org/topic_tools/drop could be used to reduce the rate of a topic, however if you like to have the imu at a higher rate and all other topics at a lower rate, it would require about 5 additional nodes.

I think I can add the change here, just need to think of a logical and intuitive way of naming things.

**Comment by cosama** [comment]
Close this in favor of https://github.com/dawonn/vectornav/pull/97

**Pull request closed without merging**
