### PR TITLE
adjust ROS header time stamp according to sensor time

### PR DESCRIPTION
**Pull request by berndpfrommer**
Fix for issue #87

In the current implementation the header.stamp time is generated by a call to the ROS node's now() method. This means the time stamp is generated when the callback from the vectornav driver happens. However there seems to be no guarantee that the callback happens right away when the data arrives at the driver level. This results in poor header time stamp quality.

This PR adjust the time stamps by computing an exponential moving average of the difference between ROS system and sensor provided time, then using that difference to compute the ROS time stamps from the sensor time.

Attached is a graph of  header time stamps (count is along x axis, time stamp value in seconds is along y axis) that shows the improvement in quality.
vn100_timestamps

### CODE REVIEW

**Comment by zzodo** [comment]
I was also experiencing the same issue as @berndpfrommer described in #87 while using VN100.
Thank you for your PR!

BTW, can you add this to master branch for ROS1 users?

**Comment by berndpfrommer** [comment]
I implemented the same fix for ROS1, but ... the problem hardly exists in ROS1. What gives?
Here is before and after fix:
adjustment_vn100_ros1

**Comment by zzodo** [comment]
@berndpfrommer 

Thank you again for sharing your experiment.

After reading your comment, I figured out that the issue is occurred when I launch multiple nodes.
Spending some times, I finally concluded that this behavior is due to my low-power computing board. (Intel NUC), since my desktop computer doesn't make any issue as you showed. (If you have another opinion, please let me know) 
It also affects to message publishing frequency, dropping from 200Hz to 185-190 hz...

So I write a few lines to deal with parse and publish ros topics in another thread, and changed the sensor callback function to push-back packet data into queue.
This improved dropped frequency and fluctuating timestamps a little, but still the problem remains.

Although it is not related to this PR, can you give me some idea?

**Comment by berndpfrommer** [comment]
I think there is room for optimization, definitely for the ROS2 driver. For instance it calls publish() even when there are no subscribers. But one thing at a time.
I will submit a PR for the ROS1 branch. It will not really help real-time issues but it should improve the quality of VI state estimation when running under heavy load.

**Comment by berndpfrommer** [comment]
The data collected to derive the above graph was junk. It was compromised by a bug, see issue #94. Please ignore the graph, the actual improvement in delta_t is dramatically better than what the graph above suggests.
The correct graph is shown in PR #95.

**Comment by zzodo** [comment]
@berndpfrommer 
Thank you for sharing 😄

**Pull request merged**
